#!/usr/bin/env d2 --animate-interval 1000
#
#  Author: Hari Sekhon
#  Date: 2023-05-03 21:57:14 +0100 (Wed, 03 May 2023)
#
#  vim:ts=2:sts=2:sw=2:et:filetype=d2
#
#  https://github.com/HariSekhon/Diagrams-as-Code
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

direction: right

classes: {
  common: {
    shape: image
    style.opacity: 0
  }
}

code: Code {
  class: common
  icon: https://cdn-icons-png.flaticon.com/512/6463/6463383.png
}
git: Git {
  class: common
  icon: https://icons.terrastruct.com/dev%2Fgit.svg
}
github: GitHub {
  class: common
  icon: https://icons.terrastruct.com/dev%2Fgithub.svg
  # icon: https://icons.terrastruct.com/social%2F039-github.svg
}
cicd: CI/CD {
  class: common
  icon: https://diagrams.mingrammer.com/img/resources/onprem/ci/github-actions.png
}
boom: Boom {
  class: common
  icon: https://www.freeiconspng.com/download/9158
}
# wink: {
#  icon: http://s3.amazonaws.com/pix.iemoji.com/images/emoji/apple/ios-12/256/winking-face.png
#  class: common
#  style: {
#    font-color: white
#  }
# }

code -> git: commit {class: common}
git -> github: push {class: common}
github -> cicd: trigger {class: common}
cicd -> boom: action {class: common}

steps: {
  1: {
    code.style.opacity: 1
  }
  2: {
    (code -> git)[0].style.opacity: 1
  }
  3: {
    git.style.opacity: 1
  }
  4: {
    (git -> github)[0].style.opacity: 1
  }
  5: {
    github.style.opacity: 1
  }
  6: {
    (github -> cicd)[0].style.opacity: 1
  }
  7: {
    cicd.style.opacity: 1
  }
  8: {
    (cicd -> boom)[0].style.opacity: 1
  }
  9: {
    boom.style.opacity: 1
  }
  §
}
