#!/usr/bin/env d2
#
#  vim:ts=2:sts=2:sw=2:et:filetype=d2
#
#  Author: Hari Sekhon
#  Date: 2024-09-12 01:14:18 +0200 (Thu, 12 Sep 2024)
#
#  https///github.com/HariSekhon/Diagrams-as-Code
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                     P r o m e t h e u s   &   T h a n o s
# ============================================================================ #

title: {
  label: Prometheus & Thanos
  near: top-center
  shape: text
  style.font-size: 40
  style.underline: true
}

classes: {
  thanos: {
    label: Thanos
    icon: https://diagrams.mingrammer.com/img/resources/onprem/monitoring/thanos.png
    shape: image
  }
  prometheus: {
    label: Prometheus
    icon: https://diagrams.mingrammer.com/img/resources/onprem/monitoring/prometheus.png
    shape: image
  }
  exporter: {
    label: Prometheus\nExporters
    icon: https://diagrams.mingrammer.com/img/resources/onprem/monitoring/prometheus.png
    shape: image
  }
  alertmanager: {
    label: Prometheus\nAlertManager
    icon: https://diagrams.mingrammer.com/img/resources/onprem/monitoring/prometheus.png
    shape: image
  }
  grafana: {
    label: Grafana
    icon: https://diagrams.mingrammer.com/img/resources/onprem/monitoring/grafana.png
    shape: image
  }
  pagerduty: {
    label: Pagerduty
    icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/pagerduty.svg
    shape: image
  }
}

grafana.class: grafana

thanos_querier.class: thanos
thanos_querier.label: Thanos\nQuerier
thanos1.class: thanos
thanos2.class: thanos
thanos3.class: thanos

prometheus1.class: prometheus
prometheus2.class: prometheus
prometheus3.class: prometheus

exporter1.class: exporter
exporter2.class: exporter
exporter3.class: exporter

alertmanager.class: alertmanager

pagerduty.class: pagerduty

grafana -> thanos_querier: {label: query}

thanos_querier -> thanos1 -> prometheus1: {label: query}
thanos_querier -> thanos2 -> prometheus2: {label: query}
thanos_querier -> thanos3 -> prometheus3: {label: query}

prometheus1 <-> exporter1: {
  label: metrics polling
  style.stroke-dash: 5
}
prometheus2 <-> exporter2: {
  label: metrics polling
  style.stroke-dash: 5
}
prometheus3 <-> exporter3: {
  label: metrics polling
  style.stroke-dash: 5
}

# invisible: {
#  width: 1
#  height: 1
#  style.opacity: 0
# }

# arrows to a blank space and then more arrows from blank to alertmanager doesn't look nice
# prometheus1 -> invisible -> alertmanager
# prometheus2 -> invisible -> alertmanager
# prometheus3 -> invisible -> alertmanager

prometheus1 -> alertmanager: {label: alerts}
prometheus2 -> alertmanager: {label: alerts}
prometheus3 -> alertmanager: {label: alerts}

alertmanager -> pagerduty: {label: alerts}
