#!/usr/bin/env d2 --theme 200 --sketch
#
#  Author: Hari Sekhon
#  Date: 2024-10-05 03:22:36 +0300 (Sat, 05 Oct 2024)
#
#  vim:ts=2:sts=2:sw=2:et:filetype=d2
#
#  https://github.com/HariSekhon/Diagrams-as-Code
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

title: {
  label: "I don't always test my Ideas...\nbut when I do...\nI do it in Production!"
  near: top-center
  shape: text
  style.font-size: 40
}

classes: {
  karl_marx: {
    label: Karl Marx
    icon: images/karl_marx.webp
    shape: image
    width: 300
    height: 300
  }

  ideas: {
    label: Ideas
    icon: https://cdn-icons-png.flaticon.com/128/427/427735.png
    shape: image
  }

  buildings: {
    label: Buildings
    icon: https://cdn-icons-png.flaticon.com/128/916/916771.png
    shape: image
  }

  ruins: {
    label: Ruins
    icon: https://cdn-icons-png.flaticon.com/512/5087/5087623.png
    shape: image
  }

  factories: {
    label: Factories
    icon: https://cdn-icons-png.flaticon.com/128/2576/2576581.png
    shape: image
  }

  people: {
    label: People
    icon: https://cdn-icons-png.flaticon.com/128/900/900783.png
    shape: image
  }

  convict: {
    label: Prisoner
    icon: https://cdn-icons-png.flaticon.com/128/10295/10295613.png
    shape: image
  }

  jail: {
    label: Gulag
    # icon: https://cdn-icons-png.flaticon.com/128/40/40188.png
    # icon: https://cdn-icons-png.flaticon.com/128/3863/3863097.png
    icon: https://cdn-icons-png.flaticon.com/128/8233/8233302.png
    shape: image
  }

  boom: {
    label: War
    icon: https://img.freepik.com/premium-vector/isolated-explosion-icon-black-background-cartoon-comic-boom-effect_613284-532.jpg
    shape: image
  }

  skull: "" {
    label: Death
    icon: https://cdn-icons-png.flaticon.com/128/7714/7714654.png
    shape: image
  }
}

karl_marx.class: karl_marx
ideas.class: ideas

production: Production {
  people.class: people

  buildings.class: buildings

  factories.class: factories

  people2.class: people

  buildings2.class: buildings
  buildings2.label: Means of\nProduction
}

karl_marx -- ideas: write {style.animated: true}

ideas -> production: test {style.animated: true}

production -> results: {style.animated: true}

results: {
  # ruins.class: ruins

  convict.class: convict

  jail.class: jail

  boom.class: boom

  skull1.class: skull

  ruins2.class: ruins
}
